### ISSUE TITLE
A factor of sqrt(M_PI) instead of just M_PI in '2dfourier/src/fourier-decomp.c'

### ISSUE THREAD

**Issue by kaisershafi** [jackdawjackdaw/2dfourier#1]
Dear Chris,
I was using this code to do FBD. But in ['2dfourier/src/fourier-decomp.c'](https://github.com/jackdawjackdaw/2dfourier/blob/c35fe8becd2ac43c2c096fac620ea437aed62dd0/src/fourier-decomp.c#L165) there is a 'sqrt(M_PI)' factor instead of just 'M_PI' as in equation (4) of https://arxiv.org/pdf/1204.5774.pdf
Would you please explain?

Thanks,
Kaiser.

**Comment by jackdawjackdaw** [comment]
Hi, I suspect this is a mistake in the code, not looked at this in a decade
but I suspect it doesn't especially matter how you normalize the
coefficients as long as you're consistent. The normalization in the article
is to the area of the circle the functions have support on I believe.

Feel free to modify as you see fit.

**Comment by kaisershafi** [comment]
Thanks a lot for the reply.
